### ISSUE TITLE
Use in next.js, refresh page component reload, there is a flash situation, what should I do?

### ISSUE THREAD

**Issue by Puyi229822** [sneas/img-comparison-slider#142]
Maybe because of the problem of loading css order, what can I do in Next.js, ask for help

**Comment by sneas** [comment]
You'll need to have this CSS added somewhere  before the `<img-comparison-slider>` tag https://cdn.jsdelivr.net/npm/img-comparison-slider@8/dist/styles.css

This CSS is distributed via NPM and can be found in `dist/styles.css` folder of the component.

**Comment by kkyr** [comment]
I am getting flashing despite the suggested solution.

I have this in my React component:

```js
"use client";
import { ImgComparisonSlider } from "@img-comparison-slider/react";

...

<ImgComparisonSlider hover="hover">
  <img slot="first" src="/placeholder.svg" />
  <img slot="second" src="/placeholder.svg" />
</ImgComparisonSlider>
```

And in my `globals.css`:

```css
img-comparison-slider {
  visibility: hidden;
}

img-comparison-slider [slot='second'] {
  display: none;
}

img-comparison-slider.rendered {
  visibility: inherit;
}

img-comparison-slider.rendered [slot='second'] {
  display: unset;
}
```

Any suggestion on what I could try?
